=== repagh/WorldListener/OpenALListener/openalworld.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://dueca.tudelft.nl"
           xmlns="https://dueca.tudelft.nl"
           elementFormDefault="qualified">

  <!-- Main element, graphics world -->
  <xs:element name="world">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded" minOccurs="0">
        <!-- templates group the definition of objects in the world -->
        <xs:element name="template" type="template_t"/>
        <!-- Statics group the instantiation of static objects in the world -->
        <xs:element name="static" type="static_t"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>

  <!-- Each declaration is named, has a type which corresponds to an available
       object type created somewhere in a factory, and a key by which
       it can be created. The key may match on a channel entry -->
  <xs:complexType name="template_t">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="param" type="param_t"/>
      <xs:element name="file" type="xs:string"/>
    </xs:choice>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="type" type="xs:string" use="required"/>
    <xs:attribute name="key" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="param_t">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- A static instantiates a fixed object
       The static provides the name, type and coordinates and file name(s). -->
  <xs:complexType name="static_t">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="param" type="param_t"/>
      <xs:element name="file" type="xs:string"/>
    </xs:choice>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="type" type="xs:string" use="required"/>
  </xs:complexType>

</xs:schema>

=== repagh/WorldListener/OpenALListener/openalworld.xml
<?xml version='1.0' encoding='UTF-8'?>
<world xmlns="https://dueca.tudelft.nl"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://dueca.tudelft.nl openalworld.xsd">

  <template type="moving_relative looping" key="AudioObjectMotion:mosquito">
    <param name="volume">0.99</param>
    <param name="pitch">2.0</param>
    <file>mosquito.wav</file>
  </template>
  <static type="constant looping" name="gearup2">
    <file> PA34_gear_up.wav</file>
    <param name="volume">0.3</param>
  </static>
</world>
